### PR TITLE
Property Edit Frontend UI

### PR DESCRIPTION
**Pull request by altam-sh**
- Added Edit button in PropertyDetailsPage
- Edit Button toggles a Modal which overlays Edit UI
- Edit UI is in its own EditPropertyComponent. (can also be added to the MGMT Dashboard if desired)
- Edit UI Connected to the Prop Information of the Property
- Delete Modal and Save Edit Buttons implemented, just missing the logic function added.
- Added edit button onto CondoMGMTComponent

### CODE REVIEW

**Review by layanat — COMMENTED** [review]
Great UI for the Edit property Form it is looking clean!
Just a few remarks (considering the edit button behavior has not been Implemented yet)
1- The Edit button on the Property's dashboard is making the page look a bit clustered -too many buttons. I think you dont really need it as the user should edit from the details page where we already have the edit button.
So maybe just link that button to edit property instead

2- I would put the cancel button in the edit property either inside the container as a button by itself ( two small buttons and one big one under it) OR i would make a small x in the top corner to close the container ( look into font awesome styling) 

Im assuming the functionality for editing and deleting has not been implemented yet, so not commenting on that.

**Comment by zaheerqur** [comment]
**Code Management and Quality Review**

1. Branch Naming: Consider using more descriptive branch names, such as edit-property-ui-improvements, for better context.
2. Commit Messages: The commit messages are clear and descriptive, showcasing good practices.
3. Atomic Commits: Commits are well-structured and atomic, each representing a single logical change.

**Code Quality Highlights**

1. Consistency and Readability: The code follows consistent naming conventions and formatting, enhancing readability.
2. Error Handling: Graceful error handling using try-catch blocks and informative error messages with toast.error.
3. Validation: Robust form validation ensures that incomplete data cannot be submitted.
4. Component Structure: Logical structuring of EditPropertyComponent with clear separation of concerns.

**Suggestions for Improvement**

1. Expand Test Coverage: Increase test coverage to include more user interactions and edge cases for improved reliability.

**Review by zaheerqur — APPROVED** [review]
Left a detailed comment earlier, solid work. Good for merging into main!

**Comment by altam-sh** [comment]
Thank you for your comments @layanat I took them into consideration when finishing the page and removed the edit button as suggested. I also refactored the cancel and delete button as per your suggestions. 
I also appreciate you taking the time to explain the conventions on github and implemented the atomic commits in the latter part of this page's implementation. For the branch name I will make sure to follow that naming convention for future pull requests.

**Comment by altam-sh** [comment]
Thank you @zaheerqur for the review and for the kind words, I do appreciate it a lot. I will be working on the tests with the correct branch naming convention shortly. Thank you for merging !

**Pull request merged**
