### PR TITLE
UI request form

### PR DESCRIPTION
**Pull request by Dom-Isbis**
Implementing the frontend for the request form. First, I added a button on the condo details page "Create Request". Then, implemented the request form page. The new button links to the request form.

### CODE REVIEW

**Comment by laurenrigante** [comment]
Just some comments on the general css.

- I think the title of the page condo+unitNumber should be higher up on the page. It is low compared to the other pages on the website. Also, the color of the title doesnt match the other page  titles (see dashboard, mgmt dashboard, property details page for color and sizing reference ). On thise pages, the page titles have  #4540db, whereas yours is  #2f2c9b

image

- I think the labels should be left justified. The other forms on the website follow this convention so i think yours should too

image

- the cancel and submit button should be within the actual component, not outside. Once again this is jsut a convention all the other forms on the website follow

image


heres an example of the left justified fiels in the add condo form as well as the buttons inside the component


image


- The form should also have a title in the actual form component. something like "Submit Request" or "Your Request" "Send Request" not sure but all forms usually have titles in them on our site. The title of the form should be the colour you used  for the page title :   #2f2c9b


- lastly, your textarea is the default textarea styling. Could you add styling so it matches the style of the site? 
 personally, i dont think the textarea should be expandable by the user.

image


image


 i think we should pick a set height(i would say something in the medium range.. i dont think these description messages are intended to be long anyways). see below

image

I would also change the placeholder text to a darker blue that is in the shade range of our website. The rest of the styling (border color, width, size) is up to you


If you need any inspiration or references for colours, sizing, and styles, feel free to look at the other forms on the website :)

**Comment by laurenrigante** [comment]
Lastly, there is a bug with the footer on your page. Im not sure what it causing it but here is what teh footer looks like 
the styling has been affected. 

image

and here is what it looks like on the condo details page


image


im not sure what is causing it but it has to be resolved before we merge :)

**Review by laurenrigante — CHANGES_REQUESTED** [review]
see comments under PR

**Comment by layanat** [comment]
I agree, to keep it uniform with our other forms ( log in , sign up, property and condo forms) the buttons should be in the container and the text should be left justified as well as a title.
I also tried it on my end and the footer looks the same as the screenshot, i think it has to do with your div tags placements

**Comment by laurenrigante** [comment]
The ui looks great!!! goodjob.

For the toasts- i would remove the hideprogressbar that you put in the toastcontainer (line 67). All of the other toasts on the website have the progress bar and yours is the only one that doesnt so it feels inconsistent. It also gives the usr the idea that they have to manually close the toast themselves, beccause they cant see that it is being timed. 

 i would also change the value of the toast and remove the red writing under the form
image

the point of react toasts is to remove the need for the red writing in the form so i would change the value of the toast to be something more descriptive that tells the user **why**  their submit failed and remove this red writing. 
If the user doesnt fill out the description field and presses submit, a toast error should be thrown to indicate to the user that it failed bc missing mandatory fields were not filled. I think i would change it to "Please fill all fields", 

the toast for error submitting request (line 37)  should be thrown if there is an issue with the backend sending/receiving the data, something that is not up to the user to fix. So i would still keep this toast but instead of  doing throw new errorr "not 15 words long" (line 25)

i would toast.error ("fill all fields)


also, i would revert your dropdown options back to what you had them as. Before, your options followed exactly what was written in the requirements which is good. Now they are vaguer- im not sure what an administrative or financial request is. 



lastly, for the mandatory description condition, i wouldnt enforce a 15 word minimum limit, i would simply enforce that the field is not empty. If someone is requesting an elevator reservation for move in date for example , they should be able to simply write 
"requesting elevator reservation for move in on 2024-06-17 at 10 am"  which is 11 words for example
or if they need maintenance, they should be able to write "clogged toilet"  etc

**Comment by laurenrigante** [comment]
I have realized there is a bug in your css that is affecting the styling of our other pages.


for example, the footer bug has mostly been fixed but the height of the footer is too long now. The user profile page has also been affected by ur css

### here is what the user profile looks like on your branch vs main
image

image




### here is what the footer looks like on your branch vs main
image

image


i think this issue is arising because of classnames. I have not verified yet- but i noticed you are using similar classnames to userprofile and footer, and i think your css is overriding the other pages css as well.

for exmaple here is your css for container in request form
image


but it is affecting the css of the footer container as well as the css of the container in the userprofile
image

**Review by laurenrigante — COMMENTED** [review]
- Tests are passing with 90% coverage for the form
- UI bugs for profile and footer have been resolved

Great UI! Waiting to discuss dropdown options with team before merge but other than that it is good to go

**Review by laurenrigante — CHANGES_REQUESTED** [review]
Looks good, few things

1) for the title condo+unitnumber, could you please call the correct backend functions to get the actual value of this field instead of leaving the static one? the condo details page is updated and working so you should be able to successfully get the condo unit number to display

2) your text area length is still editable by the user. i added this !important tag and it seemed to fix it and make it not editable anymore
image

3) create request button is missing the onhover effect

4) For the cancel button, can we change it to a grey colour and add teh hover effect? i believe its this color : #6c757d but it would be best to check with alta and zaheer

5) the options in the dropdown are good, but as we spoke about in the meeting there is only 3 categories for them in the backend. we need to categorize these options into 3 --> financial, admin, maintenance. Maybe we could give each one an id
EXAMPLE: financial requests ="1", admin requests="2", maintenance requests="3". We then need to send this to the backend instead of the string
also, leo has asked if we can add "payment invoice" and "Tax letter by mail" as options ( these would be considered financial options). For any questins about this, plz redirect to the backend channel on the discord


6) the open/close behaviour of the modal is a bit strange. As a user, i would expect that once my request is sent successfully and iget the successful toast message, that the modal would close. but isntead it just stays  open
image

adding this line in the successful branch closes the modal as soon as the request is successfully sent



Lastly, the behaviour of the toasts is strange. IF you close the modal while a toast isnt being done displaying, and then reopen the modal- the toast restarts. see this video, the same happens with success toasts. Im honestly not sure if there is even a way to fix this, but i thought i would bring it up

https://www.loom.com/share/a525cbe650b740c1bbec19c7f48ce3d6

**Comment by laurenrigante** [comment]
Also, this code is currently not being covered in the tests. As of right now, your form is at 9% coverage
 Plz add tests to all files that have been altered by ur code (example: u will have to add tests in condodetails page now that you have added a button to it)

**Comment by layanat** [comment]
Request form modal UI looks good
Aside from the weird toast behavior in screenshot below:
image

On filling out a moving request ( first option) the form is toasting an error to fill our all fields 
https://www.loom.com/share/73f3e025654f4b3a94c7aa813552af9e

Also we are still missing the Tax letter by mail"  request option

**Review by laurenrigante — APPROVED** [review]
UI looks great, form is working well as of right now. Ready for merge

**Pull request merged**
