### PR TITLE
Property Files button, PropertyFilesPage, and PropertyFilesComponent

### PR DESCRIPTION
**Pull request by Yason287**
I created a few pages, which are CondoFilesPage.jsx, CondoFilesPage.css, CondoFilesComponent.jsx,  CondoFilesComponent.css.
Please review it when you have time.

### CODE REVIEW

**Review by layanat — COMMENTED** [review]
Looking good so far in terms of having everything in one component! Great job on that
I have some suggestions for you
Condo Files Button: 
1- The Condo FIles button ideally should be named Add Property Files instead.
2- I would suggest changing The Condo Files button's current placement. Maybe add it directly under the Property Title and center it ?

**Comment by layanat** [comment]
Add Condo Files page:
1- When you Choose to upload, it directly adds it to the list of uploaded files even without pressing the "Upload" Button. It seems like the upload button has no functionality now? Not sure if im misunderstanding how it is supposed to work?

2- If you press on on a file manually and then drag and drop a file, it does delete the first one you tried to manually upload. Instead, the dropped file will go immediately in the list of uploaded files, and the one you tried to manually upload stays in the upload field.

3- Unable to upload multiple files. If I upload a file, and it gets saved in the uploaded files, I expect the upload field to clear up so that I can upload a new one which then should be added to the list of files i already uploaded  , not replace them. 

4- I am not sure I understand why there is " Uploaded Files" and also Files Associated with this condo? If you mean that uploaded files are the ones you are currently uploading and files associated with condo are the ones already existing, then maybe you should have a save button to move uploaded files into files associated with condo once you are done uploading? Also Instead of naming it Files Associated with condo, I would probably suggest naming it Files Associated with {Property Name}

5- I also tried to use the cancel button to cancel a file i uploaded, but it is not doing anything

**Comment by layanat** [comment]
Lastly,
For the upload field, You can use our styling link that we have on the other forms to make it look the same. 
This is how it looks like on the other forms: 
image

this is the styling link you can add to make it look like this ( you can find it in PropertyForm and AddCondoForm)
image

**Review by layanat — COMMENTED** [review]
I think you meant to say that if a property is created without condos , then the button does not appear. But I think it should still appear because these are property files not condo files.
Would still recommend you take opinions of other team members for this one

**Comment by laurenrigante** [comment]
i agree with layana to change the condo files button placement to higher on the page near the title. However, it shouldnt be centered because it will have to be next to the edit button. It should either be left or right

**Comment by laurenrigante** [comment]
responsiveness of page is really nice.
- drag and drop feature works great, allowing you to select multiple files at a time and upload in 1 shot.
-  Choose files also allows you to select and upload multiple files at a time which is great

to work on
- i think you should make the fonts in the buttons smaller. they are really big in the page and it also is affecting the responsiveness of the upload files button

image

- the cancel button needs to be changed to grey, as voted on in the channel as a team. red is now reserved only for delete

- if i am uploading something using the choose files button, even after i click upload it doesnt clear the choose files. Im not sure if this is considered a bug or not, as it technically does not affect the way the page works so i think its probably ok for now.
https://www.loom.com/share/47ea8b58ddeb4fada9c578451e3f4549


- the font in the close button when u are viewing a file is really small, i would enlarge it a bit
image

i made it a big larger using font-size:larger
image



** IMPORTANT **
your button css is affecting all other buttons on the website, please find this error and fix it, as it is affecting the components
now, all the writing on all buttons on the website is the same size as the buttons on ur page. This usually happens when u are using the same classname as other pages, or if u are directly affecting alll buttons. 

image

**Pull request closed without merging**
