### PR TITLE
US10 - edit/delete property/condo

### PR DESCRIPTION
**Pull request by zaheerqur**
1. Edit and Delete Condo Functions are working as expected.
2. Delete Property Function also works fine. 
3. Edit Property however has some issues with the way its being handled in the EditPropertyComponent, will continue working on a fix.

image
image
image
image

### CODE REVIEW

**Review by laurenrigante — CHANGES_REQUESTED** [review]
### **EDIT AND DELETE CONDO**
- there should be validation for editing condo (See video) - when editing they should not be able to submit empty fields that are required in the condo creation. During condo creation- all fields are empty
https://www.loom.com/share/c3fdabe82d264a67a99fa5216814ddfa?sid=ba8087be-b472-4a80-b32d-00265b4aff46
- the locker and parking should not be a text field, its a textbox in the condo creation form so the user should not be able to write something there?  it should be a checkbox of whether or not they have a locker or not
- no validation for invalid inputs, you shouldnt be able to input negative numbers for prices and random chars like -[]'/;.. youu also shouldnt be able to add text in a numeric field.

image


- delete condo works as expected



### ** EDIT AND DELETE PROPERTY**

 Same problem for edit property apply, user should not be able to submit the edit property with empty mandatory fields.

the form needs validation for inputs as well

**Comment by altam-sh** [comment]
The Functionalities as far as Edit and Delete of both Condo and Property work fine by my testing, great work! 
The validations of Empty Fields and Special Characters work well on both forms too. 

The only things worth noting is that in the validation of the Property Edit form, I believe the limit of Locker Count and Parking Count should be set to 30 instead of 499. 
Additionally, the verification works correctly on the Condo Edit form, but there is no Toast or prompt that appears indicating when a verification check is violated the way that it does on the Property Form. 
Lastly, for the Condo Edit Form, the Unit Number should allow for special characters.

Other than those little changes, the functionalities themselves work as expected, well done!

**Comment by layanat** [comment]
I agree with alta,
It is important to limit those to 30 to avoid overflowing our DB. It is all implemented in Property Form you can follow the same validation process 
image

image

**Comment by layanat** [comment]
I would suggest removing any restrictions you have on Unit Number

**Comment by layanat** [comment]
Also dont forget to add documentation to your pages before merging!

**Review by laurenrigante — APPROVED** [review]
goodjob, changes have been correctly implemented.

**Pull request merged**
