### PR TITLE
Refactored code in user profile.

### PR DESCRIPTION
**Pull request by mattflahertyy**
…l refresh

### CODE REVIEW

**Comment by leobrod44** [comment]
Please relate the specific bug issue under development and change the title

**Comment by leobrod44** [comment]
Also, it says still cant see profile pic, is it fixed or not?

**Comment by mattflahertyy** [comment]
> Also, it says still cant see profile pic, is it fixed or not?

I fixed a small issue that lauren had but didn't fix visually seeing the profile change

**Comment by leobrod44** [comment]
I removed mention of the "still cant see picture"

**Review by leobrod44 — APPROVED** [review]
Good refactor

**Pull request merged**
