### PR TITLE
US9 - creation of File Upload

### PR DESCRIPTION
**Pull request by Yason287**
Please review and merge if everything is ok. There is an issue with PropertyDetailsPage, the pagination is on the left instead of in the center. Probably, there was some error when I was resolving conflicts during the pulling from main. Otherwise everything should be ok.

### CODE REVIEW

**Comment by layanat** [comment]
Code  management review:
Please change the title of Your PR To US # T # short description of the task (For example Implement Condo Files Upload)
Please link your US in the development section, if you do not find one you need to create it in the issues section with assigning label task to it and then link it to your PR

**Review by layanat — CHANGES_REQUESTED** [review]
Looks good! Please resolve your merge conflicts

**Comment by laurenrigante** [comment]
its good, but i still find it confusing the difference between upload files and files associated with prpoerty ...

i think we should change the text of "uploaded files" , that texts makes it seem like the files have already been uploaded, which implies to the user that they do not have to click  the upload  files button.

I think something like "selected files" might be better.. 
image

image

**Review by layanat — APPROVED** [review]
Change is looking good, and UI is good. Good work

Validation for empty submission pushed till next sprint
Approving and merging

**Comment by layanat** [comment]
Code management :
For your future Branches, please follow correct name convention and link your issues to your commits
You can check the explanation for this on discord 
Exanple
Added feature X #XXX

**Pull request merged**
